---
- name: Install nginx
  ansible.builtin.apt:
    name: [nginx]
    state: present

- name: Install certbot
  ansible.builtin.apt:
    name: [certbot, python3-certbot-nginx]
    state: present

- name: Deploy nginx files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
    backup: true
  with_items:
    - src: nginx/custom.conf.j2
      dest: /etc/nginx/conf.d/custom.conf
  notify: Restart nginx

- name: Disable default vhost
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Enable/start nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
