---
- name: Remove old motd files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/motd
    - /etc/motd.tail
    - /etc/update-motd.d/10-uname

- name: Deploy motd files
  ansible.builtin.template:
    src: scripts/motd.sh
    dest: /etc/update-motd.d/50-body
    owner: root
    group: root
    mode: "0755"

- name: Clear motd issue
  ansible.builtin.copy:
    content: ""
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - /etc/issue
    - /etc/issue.net
